### ISSUE TITLE
Add Rust API Guidelines

### ISSUE THREAD

**Issue by sunjay** [mre/idiomatic-rust#2]
The [Rust API Guidelines](https://github.com/brson/rust-api-guidelines) just got published as part of the [Libz Blitz](https://blog.rust-lang.org/2017/05/05/libz-blitz.html). Probably a good idea to include them. :smile:

**Comment by mre** [comment]
Thanks @sunjay for the suggestion. I might have overlooked something, but there already exists an entry for that. https://github.com/mre/idiomatic-rust/commit/c3e9da56441a6028bdddfcbbcba1f489487e3bc3
😉

**Comment by sunjay** [comment]
Oh! My bad! I must have missed it. Looks great! :smile:
