### ISSUE TITLE
HTML not rendered in Difficulty filter 

### ISSUE THREAD

**Issue by mart-e** [mre/idiomatic-rust#45]
![Screenshot from 2024-02-06 14-31-07](https://github.com/mre/idiomatic-rust/assets/564822/2f7c14f3-0678-46e7-8b1c-9172add0fe62)

I wanted to make a PR but I could not figured out where this was in the repo :thinking:

**Comment by mre** [comment]
Nice catch.
The code for the table is here: https://github.com/corrode/corrode.github.io/blob/master/content/idiomatic-rust/table.js

**Comment by mre** [comment]
This is fixed now; forgot to close.

![Screenshot 2024-06-04 at 19 23 41](https://github.com/mre/idiomatic-rust/assets/175809/9f54469d-9679-4a89-847b-4bc3220ae785)


https://corrode.dev/blog/idiomatic-rust-resources/
